### ISSUE TITLE
✨Design User Interface

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.FireEmoji#7]
Cc: @tkapa, @adamcogan, @bradystroud, @jernejk 

Hi @jaydenalchin,
  
### Pain
We need a nice UI for out new FireEmoji project.

### Suggested Solution
Design a simple interface for our users to input their commit message.
### Tasks

- [x] Browser / Desktop application UI Mockup
- [x] Mobile UI Mockup

Thanks!

**Comment by jernejk** [comment]
We'll do mock-ups for tool extensions and other integrations as separate issues of necessary.

Right now, we got some nice designs by @jaydenalchin. 😊
